// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRxIYEX0TlWETlHFW3o5C4WM2icOcjU40',
    appId: '1:188404721831:android:1f34bea9b425c9d46dd382',
    messagingSenderId: '188404721831',
    projectId: 'qrstock-96a80',
    storageBucket: 'qrstock-96a80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLeG3J-RJ_bk702-Z6lNF9sLfM0LGsAag',
    appId: '1:188404721831:ios:7a3c5f46a0805ac26dd382',
    messagingSenderId: '188404721831',
    projectId: 'qrstock-96a80',
    storageBucket: 'qrstock-96a80.firebasestorage.app',
    iosBundleId: 'com.example.qrstock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLeG3J-RJ_bk702-Z6lNF9sLfM0LGsAag',
    appId: '1:188404721831:ios:7a3c5f46a0805ac26dd382',
    messagingSenderId: '188404721831',
    projectId: 'qrstock-96a80',
    storageBucket: 'qrstock-96a80.firebasestorage.app',
    iosBundleId: 'com.example.qrstock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3yA5VQ_V9aQw-1nDNoERhJqe2Iq2X5Lo',
    appId: '1:188404721831:web:5bed373b9451c0b16dd382',
    messagingSenderId: '188404721831',
    projectId: 'qrstock-96a80',
    authDomain: 'qrstock-96a80.firebaseapp.com',
    storageBucket: 'qrstock-96a80.firebasestorage.app',
  );
}
